### ISSUE TITLE
点击cache时如果没有下载过点击播放不会下载，点击download每次都只会重新下载

### ISSUE THREAD

**Issue by SunshineflowerLee** [af913337456/WeChatVideoView#3]
点击cache时如果没有下载过点击播放不会下载，点击download每次都只会重新下载
ps：”能做出拍照加拍小视频部分么，最好具备视频和图片的压缩功能

**Comment by af913337456** [comment]
1，不建议从 cache 进入，仅作演示
2，注意赋予文件读取权限，download 前的缓存检测是具备的，可以查看 log
3，日后

**Comment by af913337456** [comment]
第二层次的自定义缓存路径不需要记得返回 null
