### ISSUE TITLE
设置自动播放，下载完不会自动播放

### ISSUE THREAD

**Issue by ZSFeng** [af913337456/WeChatVideoView#4]
日志报错：
D/zzzzz: 更新进度 100
D/zzzzz: 更新进度 99
D/zzzzz: 下载结束 
D/jdwp: processIncoming
D/jdwp: handlePacket : cmd=0x1, cmdSet=0xC7, len=0x14, id=0x40000A60, flags=0x0,dataLen=0x9
D/jdwp: sendBufferedRequest : len=0x34
D/zzzzz: 开始播放 
D/MediaPlayer: setDataSource()
D/MediaPlayer: Don't notify duration to com.example.asus.wechatvideoview!
D/zzzzz: 开始播放 
D/MediaPlayer: releaseSecureFlag() mWfdReceiver: null
D/MediaPlayer: setDataSource()
E/MediaPlayer: error (1, -2147483648)
D/MediaPlayer: Don't notify duration to com.example.asus.wechatvideoview!
I/SurfaceTextureClient: [STC::queueBuffer] (this:0x5c8fcc30) fps:24.91, dur:1043.74, max:238.69, min:15.19
E/MediaPlayer: Error (1,-2147483648)
D/zzzzz: 播放失败 onError 1

**Comment by af913337456** [comment]
1，检查链接的视频是否可以播放；
2，设备，尝试用此台手机，( 虚拟机的话就换手机调试 ) 播放下其它下载的视频；
参考：
http://blog.sina.com.cn/s/blog_ca2f92a00102uxsc.html
http://blog.csdn.net/baimingyong007/article/details/11772705
http://blog.csdn.net/syh63053767/article/details/8883014

**Comment by ZSFeng** [comment]
退出，重新点开就能播放了

**Comment by af913337456** [comment]
你那是播放缓存。要查清刚下载好播放不了的原因，参考下我上面的回复。因为我没碰到过你这种情况

**Comment by af913337456** [comment]
或者视频链接发出来我试试

**Comment by ZSFeng** [comment]
我就是用的demo

**Comment by af913337456** [comment]
虚拟机还是手机？

**Comment by ZSFeng** [comment]
用的手机，刚刚用其他手机测又可以了

**Comment by af913337456** [comment]
http://blog.csdn.net/syh63053767/article/details/8883014
这篇文章谈到的 5 个可能原因，4 个与手机设备损坏有关
