### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by chenmowl** [af913337456/WeChatVideoView#7]
![0](https://user-images.githubusercontent.com/12692907/33355126-1ae99872-d4f1-11e7-9a0e-2e68003ba4ac.jpg)

项目存在内存泄漏

**Comment by chenmowl** [comment]
MediaPlayer.mSurfaceHolder   SurfaceVideoView.mContext  leak

**Comment by af913337456** [comment]
是否按照要求使用? onDestory

**Comment by af913337456** [comment]
@chenmowl watch the newly commit
